### ISSUE TITLE
Objects empty

### ISSUE THREAD

**Issue by vr6syncro** [Haba1234/ioBroker.onvif#1]
`

onvif.0 | 2019-01-05 15:37:54.582 | debug | statesDB connected
-- | -- | -- | --
onvif.0 | 2019-01-05 15:37:54.568 | debug | objectDB connected
onvif.0 | 2019-01-05 15:37:51.703 | debug | cleaned everything up...
onvif.0 | 2019-01-05 15:37:51.697 | debug | cleaned everything up...
onvif.0 | 2019-01-05 15:37:49.185 | debug | ------------------------------
onvif.0 | 2019-01-05 15:37:49.185 | debug | capabilities: {"analytics":{"XAddr":"http://192.168.2.105:8080/onvif/analytics","ruleSupport":true,"analyticsModuleSupport":true},"device":{"XAddr":"http://192.168.2.105:8080/onvif/devices","network"
onvif.0 | 2019-01-05 15:37:49.185 | debug | First Live Multicast Stream: = rtsp://192.168.2.105:554/11
onvif.0 | 2019-01-05 15:37:49.185 | debug | First Live UDP Stream: = rtsp://192.168.2.105:554/11
onvif.0 | 2019-01-05 15:37:49.184 | debug | First Live TCP Stream: = rtsp://192.168.2.105:554/11
onvif.0 | 2019-01-05 15:37:49.184 | debug | Info: = {"manufacturer":"IPCAM","model":"C5F0S8Z0N1P0L0V0","firmwareVersion":"V3.1.2.66","serialNumber":"10D1DC0D38AB","hardwareId":"V3.1.2.66"}
onvif.0 | 2019-01-05 15:37:49.184 | debug | Date: = Sat Jan 05 2019 15:37:48 GMT+0100 (CET)
onvif.0 | 2019-01-05 15:37:49.184 | debug | Host: 192.168.2.105 Port: 8080
onvif.0 | 2019-01-05 15:37:49.184 | debug | ------------------------------
onvif.0 | 2019-01-05 15:37:48.993 | debug | stateChange onvif.0.discoveryRunning {"val":true,"ack":true,"ts":1546699068992,"q":0,"from":"system.adapter.onvif.0","lc":1546699068992}
onvif.0 | 2019-01-05 15:37:48.988 | debug | 192.168.2.110 8080
onvif.0 | 2019-01-05 15:37:48.988 | debug | 192.168.2.109 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.108 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.107 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.106 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.105 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.104 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.103 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.102 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.101 8080
onvif.0 | 2019-01-05 15:37:48.987 | debug | 192.168.2.100 8080
onvif.0 | 2019-01-05 15:37:48.986 | debug | Received "discovery" event
onvif.0 | 2019-01-05 15:37:28.608 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.onvif.0
onvif.0 | 2019-01-05 15:37:28.608 | warn | getDevices result: []
onvif.0 | 2019-01-05 15:37:28.593 | warn | Received "getDevices" event
onvif.0 | 2019-01-05 15:36:53.018 | debug | system.adapter.admin.0: logging false
onvif.0 | 2019-01-05 15:35:46.525 | debug | startCameras: []
onvif.0 | 2019-01-05 15:35:46.518 | debug | startCameras
onvif.0 | 2019-01-05 15:35:46.516 | info | starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.onvif, node: v8.14.0

`

Seems linke the cam was found but there are no objects only discover running.

**Comment by Haba1234** [comment]
Hello! version of the driver has long been installed? I made changes without changing the version.
