### ISSUE TITLE
Update stable version in repo from 0.0.2 to 0.4.3

### ISSUE THREAD

**Issue by GermanBluefox** [Haba1234/ioBroker.onvif#11]
# Think about update stable version to 0.4.3
**Version**: stable=**0.0.2** (529 days old) => latest=**0.4.3** (15 days old)
**Installs**: stable=**789** (72.05%), latest=**205** (18.72%), total=**1095**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L985)

**Comment by Haba1234** [comment]
Done
