### ISSUE TITLE
Could not connect to camera Hikvision DS-2CD2332-I (log added)

### ISSUE THREAD

**Issue by Andrey2509** [Haba1234/ioBroker.onvif#13]
Could not connect to camera Hikvision DS-2CD2332-I.
After scan  it shows up in the list. However, a snapshot cannot be obtained.

Debug log:
==============

onvif.0 | 2020-08-14 18:49:17.828 | debug | (7737) startCameras
-- | -- | -- | --
onvif.0 | 2020-08-14 18:49:17.828 | info | (7737) Discovery finished
onvif.0 | 2020-08-14 18:49:17.828 | debug | (7737) processScannedDevices FINISH
onvif.0 | 2020-08-14 18:49:17.828 | debug | (7737) processScannedDevices OK
onvif.0 | 2020-08-14 18:49:17.828 | debug | (7737) updateDev. resolve = OK
onvif.0 | 2020-08-14 18:49:17.827 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.recordingconfig.jobstate"
onvif.0 | 2020-08-14 18:49:17.827 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.ruleengine.tamperdetector.tamper"
onvif.0 | 2020-08-14 18:49:17.826 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.ruleengine.fielddetector.objectsinside"
onvif.0 | 2020-08-14 18:49:17.826 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.ruleengine.linedetector.crossed"
onvif.0 | 2020-08-14 18:49:17.825 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.ruleengine.cellmotiondetector.motion"
onvif.0 | 2020-08-14 18:49:17.824 | debug | (7737) updateDev. updateState = "192_168_2_20_80.message.videosource.motionalarm"
onvif.0 | 2020-08-14 18:49:17.809 | debug | (7737) создать sub_obj: [{"nameObj":"videosource.motionalarm","nameValue":"State","nameType":"boolean"},{"nameObj":"ruleengine.cellmotiondetector.motion","nameValue":"IsMotion","nameType":"boolean"},{
onvif.0 | 2020-08-14 18:49:17.809 | debug | (7737) создать devData: {"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.000Z","info":{"manu
onvif.0 | 2020-08-14 18:49:17.809 | debug | (7737) создать dev_id: "192_168_2_20_80"
onvif.0 | 2020-08-14 18:49:17.808 | debug | (7737) processScannedDevices. currDevs.indexOf(dev.id) = -1
onvif.0 | 2020-08-14 18:49:17.808 | debug | (7737) processScannedDevices. dev = {"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.000Z","
onvif.0 | 2020-08-14 18:49:17.808 | debug | (7737) processScannedDevices. devices = [{"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.00
onvif.0 | 2020-08-14 18:49:17.808 | debug | (7737) processScannedDevices. currDevs = []
onvif.0 | 2020-08-14 18:49:17.807 | debug | (7737) processScannedDevices. result = []
onvif.0 | 2020-08-14 18:49:17.791 | debug | (7737) processScannedDevices
onvif.0 | 2020-08-14 18:49:17.790 | debug | (7737) Discovery devices: [{"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.000Z","info":{"m
onvif.0 | 2020-08-14 18:49:17.790 | debug | (7737) ip_list.map result: {"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.000Z","info":{"m
onvif.0 | 2020-08-14 18:49:17.790 | debug | (7737) discoveryClassCam: 192.168.2.20:8899 - result: {}
onvif.0 | 2020-08-14 18:49:17.789 | error | (7737) CamFunc: 192.168.2.20:8899 - Error: connect ECONNREFUSED 192.168.2.20:8899
onvif.0 | 2020-08-14 18:49:17.786 | debug | (7737) discoveryClassCam: 192.168.2.20:8899
onvif.0 | 2020-08-14 18:49:17.786 | debug | (7737) discoveryClassCam: 192.168.2.20:8081 - result: {}
onvif.0 | 2020-08-14 18:49:17.784 | error | (7737) CamFunc: 192.168.2.20:8081 - Error: connect ECONNREFUSED 192.168.2.20:8081
onvif.0 | 2020-08-14 18:49:17.782 | debug | (7737) discoveryClassCam: 192.168.2.20:8081
onvif.0 | 2020-08-14 18:49:17.781 | debug | (7737) discoveryClassCam: 192.168.2.20:8080 - result: {}
onvif.0 | 2020-08-14 18:49:17.781 | error | (7737) CamFunc: 192.168.2.20:8080 - Error: connect ECONNREFUSED 192.168.2.20:8080
onvif.0 | 2020-08-14 18:49:17.779 | debug | (7737) discoveryClassCam: 192.168.2.20:8080
onvif.0 | 2020-08-14 18:49:17.778 | debug | (7737) discoveryClassCam: 192.168.2.20:8000 - result: {}
onvif.0 | 2020-08-14 18:49:17.778 | error | (7737) CamFunc: 192.168.2.20:8000 - Error: read ECONNRESET
onvif.0 | 2020-08-14 18:49:17.768 | debug | (7737) discoveryClassCam: 192.168.2.20:8000
onvif.0 | 2020-08-14 18:49:17.768 | debug | (7737) discoveryClassCam: 192.168.2.20:7575 - result: {}
onvif.0 | 2020-08-14 18:49:17.767 | error | (7737) CamFunc: 192.168.2.20:7575 - Error: connect ECONNREFUSED 192.168.2.20:7575
onvif.0 | 2020-08-14 18:49:17.759 | debug | (7737) discoveryClassCam: 192.168.2.20:7575
onvif.0 | 2020-08-14 18:49:17.759 | debug | (7737) discoveryClassCam: 192.168.2.20:80 - result: {"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T
onvif.0 | 2020-08-14 18:49:17.758 | debug | (7737) flow.series devices = {"id":"192_168_2_20_80","name":"192.168.2.20:80","ip":"192.168.2.20","port":"80","user":"andrey","password":"XXX","cam_date":"2020-08-14T13:49:15.000Z","info":
onvif.0 | 2020-08-14 18:49:17.758 | info | (7737) ------------------------------
onvif.0 | 2020-08-14 18:49:17.757 | debug | (7737) capabilities: {"analytics":{"XAddr":"http://192.168.2.20/onvif/Analytics","ruleSupport":true,"analyticsModuleSupport":true},"device":{"XAddr":"http://192.168.2.20/onvif/device_service","network
onvif.0 | 2020-08-14 18:49:17.757 | debug | (7737) First Live Multicast Stream: = rtsp://192.168.2.20:554/Streaming/Channels/1?transportmode=mcast&profile=Profile_1
onvif.0 | 2020-08-14 18:49:17.757 | debug | (7737) First Live UDP Stream: = rtsp://192.168.2.20:554/Streaming/Channels/1?transportmode=unicast&profile=Profile_1
onvif.0 | 2020-08-14 18:49:17.757 | debug | (7737) First Live TCP Stream: = rtsp://192.168.2.20:554/Streaming/Channels/1?transportmode=unicast&profile=Profile_1
onvif.0 | 2020-08-14 18:49:17.757 | info | (7737) Info: = {"manufacturer":"HIKVISION","model":"DS-2CD2332-I","firmwareVersion":"V5.2.5 build 141201","serialNumber":"DS-2CD2332-I20150320CCCH508467204","hardwareId":89}
onvif.0 | 2020-08-14 18:49:17.756 | info | (7737) Date: = Fri Aug 14 2020 18:49:15 GMT+0500 (Yekaterinburg Standard Time)
onvif.0 | 2020-08-14 18:49:17.756 | info | (7737) Host: 192.168.2.20 Port: 80
onvif.0 | 2020-08-14 18:49:17.756 | info | (7737) ------------------------------
onvif.0 | 2020-08-14 18:49:17.755 | error | (7737) 192.168.2.20 getNodes: Error: Wrong ONVIF SOAP response
onvif.0 | 2020-08-14 18:49:17.739 | error | (7737) 192.168.2.20 getConfigurations: Error: Wrong ONVIF SOAP response
onvif.0 | 2020-08-14 18:49:17.731 | error | (7737) 192.168.2.20 GetPreset Error Error: Wrong ONVIF SOAP response
onvif.0 | 2020-08-14 18:49:17.620 | info | (7737) 192.168.2.20 sub_obj: [{"nameObj":"videosource.motionalarm","nameValue":"State","nameType":"boolean"},{"nameObj":"ruleengine.cellmotiondetector.motion","nameValue":"IsMotion","nameType":"boolea
onvif.0 | 2020-08-14 18:49:17.620 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:TrackConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.620 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":[{"$":{"Name":"RecordingToken","Type":"tt:RecordingReference"}},{"$":{"Name":"TrackToken","Type":"tt:TrackReference"}}]}
onvif.0 | 2020-08-14 18:49:17.620 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.620 | debug | (7737) 192.168.2.20 Found Event - /RECORDINGCONFIG/TRACKCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:RecordingConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"RecordingToken","Type":"tt:RecordingReference"}}}
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 Found Event - /RECORDINGCONFIG/RECORDINGCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:RecordingJobConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.619 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"RecordingJobToken","Type":"tt:RecordingJobReference"}}}
onvif.0 | 2020-08-14 18:49:17.618 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.618 | debug | (7737) 192.168.2.20 Found Event - /RECORDINGCONFIG/RECORDINGJOBCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.618 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"State","Type":"xs:string"}},"elementItemDescription":{"$":{"Name":"Information","Type":"tt:RecordingJobStateInformation"}}}
onvif.0 | 2020-08-14 18:49:17.618 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"RecordingJobToken","Type":"tt:RecordingJobReference"}}}
onvif.0 | 2020-08-14 18:49:17.618 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 Found Event - /RECORDINGCONFIG/JOBSTATE
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:VideoAnalyticsConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/VIDEOANALYTICSCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.617 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:PTZConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/PTZCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:MetadataConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.616 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.615 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/METADATACONFIGURATION
onvif.0 | 2020-08-14 18:49:17.615 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:AudioOutputConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.615 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.615 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.615 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/AUDIOOUTPUTCONFIGURATION/MEDIASERVICE
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:AudioSourceConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/AUDIOSOURCECONFIGURATION/MEDIASERVICE
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:AudioEncoderConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.614 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/AUDIOENCODERCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:VideoSourceConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.613 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/VIDEOSOURCECONFIGURATION/MEDIASERVICE
onvif.0 | 2020-08-14 18:49:17.612 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:VideoEncoderConfiguration"}}}
onvif.0 | 2020-08-14 18:49:17.612 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.612 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.612 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/VIDEOENCODERCONFIGURATION
onvif.0 | 2020-08-14 18:49:17.612 | debug | (7737) 192.168.2.20 Data={"elementItemDescription":{"$":{"Name":"Configuration","Type":"tt:Profile"}}}
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Token","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 Found Event - /CONFIGURATION/PROFILE
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"IsTamper","Type":"xs:boolean"}}}
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":[{"$":{"Name":"VideoSourceConfigurationToken","Type":"tt:ReferenceToken"}},{"$":{"Name":"VideoAnalyticsConfigurationToken","Type":"tt:ReferenceToke
onvif.0 | 2020-08-14 18:49:17.611 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.610 | debug | (7737) 192.168.2.20 Found Event - /RULEENGINE/TAMPERDETECTOR/TAMPER
onvif.0 | 2020-08-14 18:49:17.610 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"IsInside","Type":"xs:boolean"}}}
onvif.0 | 2020-08-14 18:49:17.610 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":[{"$":{"Name":"VideoSourceConfigurationToken","Type":"tt:ReferenceToken"}},{"$":{"Name":"VideoAnalyticsConfigurationToken","Type":"tt:ReferenceToke
onvif.0 | 2020-08-14 18:49:17.610 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.610 | debug | (7737) 192.168.2.20 Found Event - /RULEENGINE/FIELDDETECTOR/OBJECTSINSIDE
onvif.0 | 2020-08-14 18:49:17.609 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"ObjectId","Type":"xs:integer"}}}
onvif.0 | 2020-08-14 18:49:17.609 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":[{"$":{"Name":"VideoSourceConfigurationToken","Type":"tt:ReferenceToken"}},{"$":{"Name":"VideoAnalyticsConfigurationToken","Type":"tt:ReferenceToke
onvif.0 | 2020-08-14 18:49:17.609 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.609 | debug | (7737) 192.168.2.20 Found Event - /RULEENGINE/LINEDETECTOR/CROSSED
onvif.0 | 2020-08-14 18:49:17.608 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"IsMotion","Type":"xs:boolean"}}}
onvif.0 | 2020-08-14 18:49:17.608 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":[{"$":{"Name":"VideoSourceConfigurationToken","Type":"tt:ReferenceToken"}},{"$":{"Name":"VideoAnalyticsConfigurationToken","Type":"tt:ReferenceToke
onvif.0 | 2020-08-14 18:49:17.608 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.608 | debug | (7737) 192.168.2.20 Found Event - /RULEENGINE/CELLMOTIONDETECTOR/MOTION
onvif.0 | 2020-08-14 18:49:17.608 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"HardDiskNo","Type":"xs:int"}}}
onvif.0 | 2020-08-14 18:49:17.607 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.607 | debug | (7737) 192.168.2.20 Found Event - /DEVICE/HARDWAREFAILURE/HARDDISKERROR
onvif.0 | 2020-08-14 18:49:17.607 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"HardDiskNo","Type":"xs:int"}}}
onvif.0 | 2020-08-14 18:49:17.607 | debug | (7737) 192.168.2.20 IsProperty=false
onvif.0 | 2020-08-14 18:49:17.606 | debug | (7737) 192.168.2.20 Found Event - /DEVICE/HARDWAREFAILURE/HARDDISKFULL
onvif.0 | 2020-08-14 18:49:17.606 | debug | (7737) 192.168.2.20 Data={"simpleItemDescription":{"$":{"Name":"State","Type":"xs:boolean"}}}
onvif.0 | 2020-08-14 18:49:17.606 | debug | (7737) 192.168.2.20 Source={"simpleItemDescription":{"$":{"Name":"Source","Type":"tt:ReferenceToken"}}}
onvif.0 | 2020-08-14 18:49:17.606 | debug | (7737) 192.168.2.20 IsProperty=true
onvif.0 | 2020-08-14 18:49:17.605 | debug | (7737) 192.168.2.20 Found Event - /VIDEOSOURCE/MOTIONALARM
onvif.0 | 2020-08-14 18:49:17.550 | info | (7737) 192.168.2.20 Camera supports WSPullPoint
onvif.0 | 2020-08-14 18:49:17.505 | debug | (7737) Serial Number DS-2CD2332-I20150320CCCH508467204
onvif.0 | 2020-08-14 18:49:17.505 | debug | (7737) Firmware V5.2.5 build 141201
onvif.0 | 2020-08-14 18:49:17.505 | debug | (7737) Model DS-2CD2332-I
onvif.0 | 2020-08-14 18:49:17.504 | debug | (7737) 192.168.2.20 Manufacturer HIKVISION
onvif.0 | 2020-08-14 18:49:17.477 | debug | (7737) 192.168.2.20 Device Time Fri Aug 14 2020 18:49:15 GMT+0500 (Yekaterinburg Standard Time)
onvif.0 | 2020-08-14 18:49:17.443 | debug | (7737) cam_obj: {"hostname":"192.168.2.20","username":"andrey","password":"XXX","port":"80","path":"/onvif/device_service","timeout":15000,"agent":false,"preserveAddress":true,"events":{},"
onvif.0 | 2020-08-14 18:49:17.149 | debug | (7737) state onvif.0.discoveryRunning changed: true (ack = true)
onvif.0 | 2020-08-14 18:49:17.134 | debug | (7737) discoveryClassCam: 192.168.2.20:80
onvif.0 | 2020-08-14 18:49:17.133 | debug | (7737) ip_list.map start passowrd: XXX
onvif.0 | 2020-08-14 18:49:17.133 | debug | (7737) ip_list.map start user: andrey
onvif.0 | 2020-08-14 18:49:17.133 | debug | (7737) ip_list.map start ip_entry: 192.168.2.20
onvif.0 | 2020-08-14 18:49:17.132 | debug | (7737) ip_list = ["192.168.2.20"]
onvif.0 | 2020-08-14 18:49:17.132 | warn | (7737) password = XXX
onvif.0 | 2020-08-14 18:49:17.131 | debug | (7737) discovery start
onvif.0 | 2020-08-14 18:49:17.131 | info | (7737) Discovery starting...

==============

**Comment by Andrey2509** [comment]
Version 0.2.0 and before of the adapter works fine.

**Comment by Haba1234** [comment]
Hi!
Still relevant?
The log is heavily truncated, please post a normal driver log from the file: /opt/iobroker/log

**Comment by Andrey2509** [comment]
Log file added.
[iobroker.2020-10-20.log](https://github.com/Haba1234/ioBroker.onvif/files/5408372/iobroker.2020-10-20.log)

**Comment by Andrey2509** [comment]
> Hi!
> Still relevant?
> The log is heavily truncated, please post a normal driver log from the file: /opt/iobroker/log

Log file added
[Uploading iobroker.2020-10-20.log…]()

**Comment by Andrey2509** [comment]
> Hi!
> Still relevant?
> The log is heavily truncated, please post a normal driver log from the file: /opt/iobroker/log

Log file added
[iobroker.2020-10-20.log.zip](https://github.com/Haba1234/ioBroker.onvif/files/5408394/iobroker.2020-10-20.log.zip)
