### ISSUE TITLE
Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by d16izhevsk** [Haba1234/ioBroker.onvif#2]
onvif.0 | 2019-01-29 16:21:12.501 | info | terminating
-- | -- | -- | --
onvif.0 | 2019-01-29 16:21:12.494 | error | at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)
onvif.0 | 2019-01-29 16:21:12.494 | error | at Parser.emit (events.js:211:7)
onvif.0 | 2019-01-29 16:21:12.494 | error | at emitOne (events.js:116:13)
onvif.0 | 2019-01-29 16:21:12.494 | error | at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)
onvif.0 | 2019-01-29 16:21:12.494 | error | at /opt/iobroker/node_modules/onvif/lib/utils.js:96:5
onvif.0 | 2019-01-29 16:21:12.494 | error | at MyCam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/media.js:604:13)
onvif.0 | 2019-01-29 16:21:12.494 | error | at MyCam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:131:15)
onvif.0 | 2019-01-29 16:21:12.494 | error | at MyCam.Cam.getActiveSources (/opt/iobroker/node_modules/onvif/lib/cam.js:532:20)
onvif.0 | 2019-01-29 16:21:12.494 | error | at Array.forEach (<anonymous>)
onvif.0 | 2019-01-29 16:21:12.494 | error | at MyCam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:563:76)
onvif.0 | 2019-01-29 16:21:12.494 | error | TypeError: Cannot read property 'width' of undefined
onvif.0 | 2019-01-29 16:21:12.494 | error | uncaught exception: Cannot read property 'width' of undefined
onvif.0 | 2019-01-29 16:21:01.767 | warn | getDevices result: []

**Comment by Haba1234** [comment]
Что за камера? есть еще какая то инфа для анализа?

**Comment by d16izhevsk** [comment]
Камеры dahua 4431 и китайский нонейм с регистратором класса xmeye (т.е. стандартная ситуация в большинстве домов), но так же пробовал hikvision 2cd2042 и другие.
Вероятно дело не в камерах

**Comment by Haba1234** [comment]
я подключал без проблем две разных камеры hikvision.
С другими опыта не было пока. Можете дать больше информации о проблеме? что делаете, как, что в логе с самого начала допустим со старта драйвера + скрины интересные какие

**Comment by d16izhevsk** [comment]
Поставил пароль на камеры, две из трех камер хиквижен в офисной сетке нашлось.
В китайских камерах протокол h265 включен, может в этом сложности onvif 
[https://www.dropbox.com/s/qufjqtnnwus0zy1/onvif_iobroker.JPG?dl=0](url)
[https://www.dropbox.com/s/v2iq162ohv5tp5m/onvif_log.JPG?dl=0](url)
