### ISSUE TITLE
Error with Foscam fi9900p 

### ISSUE THREAD

**Issue by Praktiker-coder** [Haba1234/ioBroker.onvif#8]
Hi,
with version > 0.0.2 i can get snapshots from my Foscam.
i've tested version 0.1.0 and 0.1.1.
Only version 0.0.2 works fine.
see error code in atached sreenshot.
IoBroker runs on a Pi 4 with IoBroker Image.
![onvif](https://user-images.githubusercontent.com/60842082/79692603-67ebc080-8266-11ea-9f13-a453e33bb635.JPG)

**Comment by Haba1234** [comment]
Hi!
0.1.2 (2020-04-19)
(haba1234) Fixed uncaught exception: The "chunk" argument must be one of type string or Buffer

**Comment by Haba1234** [comment]
Please install version 0.2.0

**Comment by Praktiker-coder** [comment]
Version 0.2.0 installed.
Works Fine.
thx.
Michael
